// -*- coding: utf-8 -*-
// This file is auto-generated by generate_seed_codes.py. Do not edit manually.
import { OMNICode } from "./registry";

export const seedCodes: OMNICode[] = [
  {
    "omni_id": "OMNI-0022558",
    "composition": {
      "target": "lumbar vertebral joints",
      "action": "bone fusion stabilization",
      "means": "metal cage and bone graft"
    },
    "plain_language": {
      "en": "Spinal fusion of the lower back (from the front)",
      "es": "Fusión quirúrgica de vértebras lumbares desde el frente",
      "fr": "Arthrodèse lombaire par abord antérieur",
      "ar": "عملية دمج وتثبيت فقرات الظهر القطنية من الأمام",
      "hi": "पीठ के निचले हिस्से के कशेरुकाओं को जोड़ने की सर्जरी",
      "zh": "前路腰椎椎体间融合内固定术",
      "pt": "Fusão cirúrgica de vértebras lombares por via anterior"
    },
    "crosswalks": {
      "cpt": "22558",
      "ichi": "KLO.JK.AA",
      "snomed_ct": "23114001",
      "icd11_pcs": "KL20.0",
      "icd10_cm": "0SG007Z"
    },
    "notes": "Arthrodesis, anterior interbody technique, lumbar spine.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0027130",
    "composition": {
      "target": "hip joint",
      "action": "joint reconstruction",
      "means": "artificial prosthetic implant"
    },
    "plain_language": {
      "en": "Total hip joint replacement surgery (Hip Arthroplasty)",
      "es": "Cirugía de reemplazo total de articulación de cadera",
      "fr": "Chirurgie de remplacement complet de la hanche (Prothèse de hanche)",
      "ar": "عملية استبدال مفصل الفخذ بالكامل بمفصل صناعي",
      "hi": "कूल्हे का जोड़ पूरी तरह बदलने की सर्जरी (हिप रिप्लेसमेंट)",
      "zh": "人工全髋关节置换术",
      "pt": "Cirurgia de substituição total da articulação do quadril"
    },
    "crosswalks": {
      "cpt": "27130",
      "ichi": "KMO.JK.AB",
      "snomed_ct": "52734007",
      "icd11_pcs": "KM20.0",
      "icd10_cm": "0SRB0JZ"
    },
    "notes": "Arthroplasty, acetabular and proximal femoral prosthetic replacement (total hip replacement).",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0027447",
    "composition": {
      "target": "knee joint",
      "action": "joint reconstruction",
      "means": "artificial prosthetic implant"
    },
    "plain_language": {
      "en": "Total knee joint replacement surgery (Knee Arthroplasty)",
      "es": "Cirugía de reemplazo total de articulación de rodilla",
      "fr": "Chirurgie de remplacement complet de la rotule (Prothèse de genou)",
      "ar": "عملية استبدال مفصل الركبة بالكامل بمفصل صناعي",
      "hi": "घुटने का जोड़ पूरी तरह बदलने की सर्जरी (नी रिप्लेसमेंट)",
      "zh": "人工全膝关节置换术",
      "pt": "Cirurgia de substituição total da articulação do joelho"
    },
    "crosswalks": {
      "cpt": "27447",
      "ichi": "KMO.JK.AA",
      "snomed_ct": "82071004",
      "icd11_pcs": "KM20.0",
      "icd10_cm": "0SRC0JZ"
    },
    "notes": "Arthroplasty, knee, condyle and patella; medial and lateral compartments (total replacement).",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0033533",
    "composition": {
      "target": "coronary arteries",
      "action": "bypass channel construction",
      "means": "vessel grafting from chest wall or leg"
    },
    "plain_language": {
      "en": "Heart bypass surgery using blood vessels (CABG)",
      "es": "Bypass cardíaco coronario con injerto de vasos sanguíneos (CABG)",
      "fr": "Pontage aorto-coronarien par greffe de vaisseaux (Pontage)",
      "ar": "عملية مجازة الشريان التاجي للقلب (ترقيع الشرايين)",
      "hi": "हृदय की धमनियों की बाईपास ग्राफ्टिंग सर्जरी (सीएबीजी)",
      "zh": "冠状动脉旁路移植造血管重建术 (心脏搭桥 CABG)",
      "pt": "Bypass cardíaco coronário com enxerto de vasos sanguíneos"
    },
    "crosswalks": {
      "cpt": "33533",
      "ichi": "KFO.JK.AA",
      "snomed_ct": "232717009",
      "icd11_pcs": "KF20.0",
      "icd10_cm": "02100A9"
    },
    "notes": "Coronary artery bypass graft (CABG), arterial bypass, 3 coronary artery grafts.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0043239",
    "composition": {
      "target": "upper digestive tract",
      "action": "endoscopic inspection and biopsy",
      "means": "flexible scope and tissue extraction instrument"
    },
    "plain_language": {
      "en": "Endoscopy of stomach and esophagus with tissue sample",
      "es": "Endoscopia de esófago y estómago con biopsia de tejido",
      "fr": "Endoscopie de l'œsophage et de l'estomac avec biopsie (FOGD)",
      "ar": "منظار المعدة والمرئ مع أخذ عينة من الأنسجة",
      "hi": "ऊपरी पेट और भोजन नली की दूरबीन जांच और बायोप्सी (ईजीडी)",
      "zh": "胃和食管镜检伴组织活检术 (胃镜)",
      "pt": "Endoscopia do esôfago e estômago com biópsia (EDA)"
    },
    "crosswalks": {
      "cpt": "43239",
      "ichi": "KCO.JK.AE",
      "snomed_ct": "118671000",
      "icd11_pcs": "KF24.0",
      "icd10_cm": "0DB64ZX"
    },
    "notes": "Esophagogastroduodenoscopy (EGD) with biopsy.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0044950",
    "composition": {
      "target": "appendix",
      "action": "total excision",
      "means": "open"
    },
    "plain_language": {
      "en": "Surgical removal of the appendix through an open incision",
      "es": "Extirpación quirúrgica abierta del apéndice",
      "fr": "Appendicectomie par voie ouverte",
      "ar": "استئصال الزائدة الدودية بالجراحة المفتوحة",
      "hi": "खुली सर्जरी द्वारा अपेंडिक्स निकालना",
      "zh": "开腹阑尾切除术",
      "pt": "Remoção cirúrgica aberta do apêndice"
    },
    "crosswalks": {
      "cpt": "44950",
      "ichi": "KBO.JK.AA",
      "snomed_ct": "32230006",
      "icd11_pcs": "LA24.0",
      "icd10_cm": "0DTJ0ZZ"
    },
    "notes": "Standard open appendectomy.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0044960",
    "composition": {
      "target": "appendix",
      "action": "total excision",
      "means": "open with drainage"
    },
    "plain_language": {
      "en": "Removal of ruptured appendix with peritoneal drainage",
      "es": "Extirpación de apéndice roto con drenaje peritoneal",
      "fr": "Ablation de l'appendice rompu avec drainage",
      "ar": "استئصال الزائدة الدودية المنفجرة مع تصريف البريتون",
      "hi": "टूटे हुए अपेंडिक्स को निकालना और निकास बनाना",
      "zh": "阑尾穿孔切除伴腹膜引流术",
      "pt": "Remoção de apêndice roto com drenagem peritoneal"
    },
    "crosswalks": {
      "cpt": "44960",
      "ichi": "KBO.JK.AZ",
      "snomed_ct": "174041004",
      "icd11_pcs": "LA24.0",
      "icd10_cm": "0DTJ0ZZ"
    },
    "notes": "Open appendectomy for ruptured appendix with abscess.",
    "provisional": true,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0044970",
    "composition": {
      "target": "appendix",
      "action": "total excision",
      "means": "percutaneous endoscopic"
    },
    "plain_language": {
      "en": "Keyhole removal of the appendix",
      "es": "Extirpación laparoscópica del apêndice",
      "fr": "Ablation laparoscopique de l'appendice",
      "ar": "استئصال الزائدة الدودية بالمنظار",
      "hi": "कीहोल (लैप्रोस्कोपिक) अपेंडिक्स निकालना",
      "zh": "腹腔镜阑尾切除术",
      "pt": "Remoção laparoscópica do apêndice"
    },
    "crosswalks": {
      "cpt": "44970",
      "ichi": "KBO.JK.AB",
      "snomed_ct": "80146002",
      "icd11_pcs": "LA24.0",
      "icd10_cm": "0DTJ4ZZ"
    },
    "notes": "Featured worked example in the SSRN paper.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0045378",
    "composition": {
      "target": "large intestine",
      "action": "endoscopic inspection",
      "means": "flexible scope"
    },
    "plain_language": {
      "en": "Routine diagnostic check of the large bowel (Colonoscopy)",
      "es": "Examen de colonoscopia diagnóstica de rutina del colon",
      "fr": "Colonoscopie diagnostique de routine",
      "ar": "منظار القولون التشخيصي الروتيني",
      "hi": "बड़ी आंत की सामान्य दूरबीन जांच (डायग्नोस्टिक कोलोनोस्कोपी)",
      "zh": "常规诊断性结肠镜检查",
      "pt": "Exame de colonoscopia diagnóstica de rotina do cólon"
    },
    "crosswalks": {
      "cpt": "45378",
      "ichi": "KDO.JK.AB",
      "snomed_ct": "73761001",
      "icd11_pcs": "KD24.0",
      "icd10_cm": "0DDB8ZX"
    },
    "notes": "Diagnostic colonoscopy, flexible, proximal to splenic flexure.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0045380",
    "composition": {
      "target": "large intestine",
      "action": "endoscopic inspection and biopsy",
      "means": "flexible scope and tissue extraction instrument"
    },
    "plain_language": {
      "en": "Colonoscopy of the bowel with tissue sample",
      "es": "Colonoscopia de colon con toma de muestra de tejido",
      "fr": "Colonoscopie du gros intestin avec biopsie",
      "ar": "منظار القولون مع أخذ عينة من الأنسجة",
      "hi": "बड़ी आंत की दूरबीन जांच और बायोप्सी (कोलोनोस्कोपी)",
      "zh": "结肠镜检伴多点组织活检术 (大肠镜)",
      "pt": "Colonoscopia do intestino grosso com biópsia"
    },
    "crosswalks": {
      "cpt": "45380",
      "ichi": "KDO.JK.AA",
      "snomed_ct": "73761001",
      "icd11_pcs": "KD24.0",
      "icd10_cm": "0DDB8ZX"
    },
    "notes": "Colonoscopy, flexible, proximal to splenic flexure, with biopsy.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0047562",
    "composition": {
      "target": "gallbladder",
      "action": "total excision",
      "means": "percutaneous endoscopic"
    },
    "plain_language": {
      "en": "Keyhole removal of the gallbladder",
      "es": "Extirpación laparoscópica de la vesícula biliar",
      "fr": "Ablation laparoscopique de la vésicule biliaire",
      "ar": "استئصال المرارة بالمنظار (ثقب المفتاح)",
      "hi": "कीहोल (लैप्रोस्कोपिक) पित्ताशय निकालना",
      "zh": "腹腔镜胆囊切除术",
      "pt": "Remoção laparoscópica da vesícula biliar"
    },
    "crosswalks": {
      "cpt": "47562",
      "ichi": "KCO.JK.AB",
      "snomed_ct": "103744009",
      "icd11_pcs": "LC20.0",
      "icd10_cm": "0FT44ZZ"
    },
    "notes": "Laparoscopic cholecystectomy.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0047563",
    "composition": {
      "target": "gallbladder",
      "action": "total excision and bile duct imaging",
      "means": "percutaneous endoscopic"
    },
    "plain_language": {
      "en": "Keyhole removal of the gallbladder with bile duct X-ray",
      "es": "Extirpación laparoscópica de vesícula con radiografía de conducto biliar",
      "fr": "Ablation laparoscopique de la vésicule avec cholangiographie",
      "ar": "استئصال المرارة بالمنظار مع تصوير القنوات المرارية",
      "hi": "पित्त नलिका के एक्स-रे के साथ पित्ताशय निकालना",
      "zh": "腹腔镜胆囊切除伴胆道造影术",
      "pt": "Remoção laparoscópica da vesícula com colangiografia"
    },
    "crosswalks": {
      "cpt": "47563",
      "ichi": "KCO.JK.AC",
      "snomed_ct": "235122005",
      "icd11_pcs": "LC20.0",
      "icd10_cm": "0FT44ZZ"
    },
    "notes": "Laparoscopic cholecystectomy with cholangiography.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0047600",
    "composition": {
      "target": "gallbladder",
      "action": "total excision",
      "means": "open"
    },
    "plain_language": {
      "en": "Surgical removal of the gallbladder through an open incision",
      "es": "Extirpación quirúrgica abierta de la vesícula biliar",
      "fr": "Ablation de la vésicule biliaire par voie ouverte",
      "ar": "استئصال المرارة بالجراحة المفتوحة",
      "hi": "खुली सर्जरी द्वारा पित्ताशय निकालना",
      "zh": "开腹胆囊切除术",
      "pt": "Remoção cirúrgica aberta da vesícula biliar"
    },
    "crosswalks": {
      "cpt": "47600",
      "ichi": "KCO.JK.AA",
      "snomed_ct": "38102005",
      "icd11_pcs": "LC20.0",
      "icd10_cm": "0FT40ZZ"
    },
    "notes": "Open cholecystectomy.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0047605",
    "composition": {
      "target": "gallbladder",
      "action": "total excision and bile duct imaging",
      "means": "open"
    },
    "plain_language": {
      "en": "Open removal of the gallbladder with bile duct X-ray",
      "es": "Extirpación abierta de vesícula con radiografía de conducto biliar",
      "fr": "Ablation de la vésicule par voie ouverte avec cholangiographie",
      "ar": "استئصال المرارة المفتوح مع تصوير القنوات المرارية",
      "hi": "खुले पित्ताशय निष्कासन के साथ पित्त नलिका का एक्स-रे",
      "zh": "开腹胆囊切除伴胆道造影术",
      "pt": "Remoção aberta da vesícula com colangiografia"
    },
    "crosswalks": {
      "cpt": "47605",
      "ichi": "KCO.JK.AD",
      "snomed_ct": "76543003",
      "icd11_pcs": "LC20.0",
      "icd10_cm": "0FT40ZZ"
    },
    "notes": "Open cholecystectomy with cholangiography.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0049505",
    "composition": {
      "target": "inguinal canal",
      "action": "repair",
      "means": "open"
    },
    "plain_language": {
      "en": "Open surgical repair of an initial groin hernia",
      "es": "Reparación quirúrgica abierta de hernia inguinal inicial",
      "fr": "Réparation chirurgicale ouverte d'une hernie inguinale initiale",
      "ar": "إصلاح الفتق الإربي بالجراحة المفتوحة لأول مرة",
      "hi": "प्रारंभिक जांघ के जोड़ की हर्निया की खुली सर्जरी",
      "zh": "初期开腹腹股沟疝修补术",
      "pt": "Reparação cirúrgica aberta de hérnia inguinal inicial"
    },
    "crosswalks": {
      "cpt": "49505",
      "ichi": "KEO.JK.AA",
      "snomed_ct": "50465007",
      "icd11_pcs": "LE20.0",
      "icd10_cm": "0YQP0ZZ"
    },
    "notes": "Open inguinal hernia repair, initial, patient 5 years or older.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0049550",
    "composition": {
      "target": "femoral canal",
      "action": "repair",
      "means": "open"
    },
    "plain_language": {
      "en": "Open surgical repair of a thigh-groin hernia",
      "es": "Reparación quirúrgica abierta de hernia femoral",
      "fr": "Réparation ouverte d'une hernie fémorale",
      "ar": "إصلاح الفتق الفخذي بالجراحة المفتوحة",
      "hi": "जांघ के हर्निया की खुली सर्जरी द्वारा मरम्मत",
      "zh": "开腹股疝修补术",
      "pt": "Reparação cirúrgica aberta de hérnia femoral"
    },
    "crosswalks": {
      "cpt": "49550",
      "ichi": "KEO.JK.AF",
      "snomed_ct": "31802008",
      "icd11_pcs": "LE20.0",
      "icd10_cm": "0YQP0ZZ"
    },
    "notes": "Open femoral hernia repair, initial.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0049585",
    "composition": {
      "target": "umbilicus",
      "action": "repair",
      "means": "open"
    },
    "plain_language": {
      "en": "Open surgical repair of a belly button hernia",
      "es": "Reparación quirúrgica abierta de hernia umbilical",
      "fr": "Réparation ouverte d'une hernie ombilicale",
      "ar": "إصلاح الفتق السري بالجراحة المفتوحة",
      "hi": "नाभि की हर्निया की खुली सर्जरी द्वारा मरम्मत",
      "zh": "开腹脐疝修补术",
      "pt": "Reparação cirúrgica aberta de hérnia umbilical"
    },
    "crosswalks": {
      "cpt": "49585",
      "ichi": "KEO.JK.AC",
      "snomed_ct": "45228008",
      "icd11_pcs": "LE20.0",
      "icd10_cm": "0WQP0ZZ"
    },
    "notes": "Open umbilical hernia repair, initial, patient 5 years or older.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0049650",
    "composition": {
      "target": "inguinal canal",
      "action": "repair",
      "means": "percutaneous endoscopic"
    },
    "plain_language": {
      "en": "Keyhole repair of a groin hernia",
      "es": "Reparación laparoscópica de hernia inguinal",
      "fr": "Réparation laparoscopique d'une hernie inguinale",
      "ar": "إصلاح الفتق الإربي بالمنظار",
      "hi": "जांघ के जोड़ (हर्निया) की कीहोल सर्जरी",
      "zh": "腹腔镜腹股沟疝修补术",
      "pt": "Reparação laparoscópica de hérnia inguinal"
    },
    "crosswalks": {
      "cpt": "49650",
      "ichi": "KEO.JK.AB",
      "snomed_ct": "233703002",
      "icd11_pcs": "LE20.0",
      "icd10_cm": "0YQP4ZZ"
    },
    "notes": "Laparoscopic inguinal hernia repair.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0049652",
    "composition": {
      "target": "umbilicus",
      "action": "repair",
      "means": "percutaneous endoscopic"
    },
    "plain_language": {
      "en": "Keyhole repair of a belly button hernia",
      "es": "Reparación laparoscópica de hernia umbilical",
      "fr": "Réparation laparoscopique d'une hernie ombilicale",
      "ar": "إصلاح الفتق السري بالمنظار",
      "hi": "नाभि की हर्निया की कीहोल सर्जरी द्वारा मरम्मत",
      "zh": "腹腔镜脐疝修补术",
      "pt": "Reparação laparoscópica de hérnia umbilical"
    },
    "crosswalks": {
      "cpt": "49652",
      "ichi": "KEO.JK.AD",
      "snomed_ct": "428784000",
      "icd11_pcs": "LE20.0",
      "icd10_cm": "0WQP4ZZ"
    },
    "notes": "Laparoscopic repair of umbilical hernia.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0049654",
    "composition": {
      "target": "abdominal wall",
      "action": "repair",
      "means": "percutaneous endoscopic"
    },
    "plain_language": {
      "en": "Keyhole repair of a surgical scar hernia",
      "es": "Reparación laparoscópica de hernia incisional",
      "fr": "Réparation laparoscopique d'une hernie incisionnelle",
      "ar": "إصلاح فتق الجرح الجراحي بالمنظار",
      "hi": "सर्जक चीरे से बनी हर्निया की कीहोल सर्जरी",
      "zh": "腹腔镜切口疝修补术",
      "pt": "Reparação laparoscópica de hérnia incisional"
    },
    "crosswalks": {
      "cpt": "49654",
      "ichi": "KEO.JK.AE",
      "snomed_ct": "429218001",
      "icd11_pcs": "LE20.0",
      "icd10_cm": "0WQP4ZZ"
    },
    "notes": "Laparoscopic repair of incisional hernia.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0052601",
    "composition": {
      "target": "prostate gland",
      "action": "partial excision",
      "means": "electrical wire cutting inside urethra"
    },
    "plain_language": {
      "en": "Prostate shaving surgery via water channel (TURP)",
      "es": "Extirpación transuretral de próstata (TURP)",
      "fr": "Résection transurétrale de la prostate (TURP)",
      "ar": "استئصال جزء من البروستاتا عبر مجرى البول (TURP)",
      "hi": "पेशाब की नली द्वारा प्रोस्टेट ग्रंथि की छंटाई (टीयूआरपी)",
      "zh": "经尿道前列腺电切修削术 (TURP)",
      "pt": "Ressecção transuretral da próstata (TURP)"
    },
    "crosswalks": {
      "cpt": "52601",
      "ichi": "KIO.JK.AB",
      "snomed_ct": "176274000",
      "icd11_pcs": "KI20.0",
      "icd10_cm": "0VT08ZZ"
    },
    "notes": "Transurethral electrosurgical resection of prostate (TURP).",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0058150",
    "composition": {
      "target": "uterus",
      "action": "total excision",
      "means": "open abdominal incision"
    },
    "plain_language": {
      "en": "Abdominal removal of the uterus (Hysterectomy)",
      "es": "Extirpación quirúrgica abdominal del útero (Histerectomía)",
      "fr": "Ablation chirurgicale de l'utérus par l'abdomen (Hystérectomie)",
      "ar": "استئصال الرحم عن طريق البطن (Hysterectomy)",
      "hi": "पेट खोलकर बच्चेदानी को बाहर निकालना (हिस्टेरेक्टॉमी)",
      "zh": "开腹全子宫切除术",
      "pt": "Remoção cirúrgica do útero por via abdominal (Histerectomia)"
    },
    "crosswalks": {
      "cpt": "58150",
      "ichi": "KHO.JK.AA",
      "snomed_ct": "80899001",
      "icd11_pcs": "KH20.0",
      "icd10_cm": "0UT90ZZ"
    },
    "notes": "Total abdominal hysterectomy, with or without removal of ovaries/tubes.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0059510",
    "composition": {
      "target": "pregnant uterus",
      "action": "surgical delivery opening",
      "means": "abdominal uterine incision"
    },
    "plain_language": {
      "en": "Cesarean section delivery (C-section)",
      "es": "Parto por operación cesárea (Cesárea)",
      "fr": "Accouchement par césarienne",
      "ar": "ولادة قيصرية (شق جراحي بالرحم)",
      "hi": "सी-सेक्शन द्वारा बच्चे का जन्म (सिजेरियन डिलीवरी)",
      "zh": "剖宫产手术分娩",
      "pt": "Parto por operação cesariana (Cesárea)"
    },
    "crosswalks": {
      "cpt": "59510",
      "ichi": "KJO.JK.AA",
      "snomed_ct": "11438009",
      "icd11_pcs": "KJ20.0",
      "icd10_cm": "10D00Z1"
    },
    "notes": "Routine obstetric care including antepartum care, cesarean delivery, and postpartum care.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0066984",
    "composition": {
      "target": "eye lens",
      "action": "total excision",
      "means": "ultrasonic fragmentation and artificial lens placement"
    },
    "plain_language": {
      "en": "Cataract surgery with artificial lens placement",
      "es": "Extirpación de catarata con colocación de lente artificial",
      "fr": "Ablation de la cataracte avec implant de cristallin artificiel",
      "ar": "إزالة المياه البيضاء وزراعة عدسة عينية صناعية",
      "hi": "मोतियाबिंद निकालना और कृत्रिम लेंस लगाना",
      "zh": "白内障超声乳化吸出及人工晶体植入术",
      "pt": "Remoção de catarata com implantação de lente artificial"
    },
    "crosswalks": {
      "cpt": "66984",
      "ichi": "KIO.JK.AA",
      "snomed_ct": "112792007",
      "icd11_pcs": "KI20.0",
      "icd10_cm": "08RJ3JZ"
    },
    "notes": "Extracapsular cataract removal with insertion of intraocular lens prosthesis.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0069436",
    "composition": {
      "target": "middle ear",
      "action": "surgical drainage opening",
      "means": "pressure-equalizing tube insertion"
    },
    "plain_language": {
      "en": "Inserting ventilation tubes into the eardrum",
      "es": "Inserción de tubos de drenaje en el tímpano",
      "fr": "Pose d'aérateurs transtympaniques (Yoyo)",
      "ar": "تركيب أنابيب تهوية وتصريف في غشاء طبلة الأذن",
      "hi": "कान के परदे में वेंटिलेशन ट्यूब डालना",
      "zh": "鼓膜切开伴压力平衡管防积水植入术",
      "pt": "Inserção de tubos de ventilação no tímpano"
    },
    "crosswalks": {
      "cpt": "69436",
      "ichi": "KLO.JK.AB",
      "snomed_ct": "25687000",
      "icd11_pcs": "KL20.0",
      "icd10_cm": "099970Z"
    },
    "notes": "Tympanostomy (requiring insertion of ventilating tube), local or general anesthesia.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0070553",
    "composition": {
      "target": "brain",
      "action": "magnetic resonance imaging",
      "means": "magnetic fields without and with contrast dye"
    },
    "plain_language": {
      "en": "Brain MRI scan (before and after contrast dye)",
      "es": "Resonancia magnética (RM) cerebral con y sin contraste",
      "fr": "IRM du cerveau avec et sans produit de contraste",
      "ar": "رنين مغناطيسي على المخ بالصبغة وبدون صبغة",
      "hi": "कंट्रास्ट डाई के साथ और बिना दिमाग का एमआरआई स्कैन",
      "zh": "脑部平扫加增强核磁共振 (MRI) 扫描",
      "pt": "Ressonância magnética (RM) cerebral com e sem contraste"
    },
    "crosswalks": {
      "cpt": "70553",
      "ichi": "VVV.AC.AA",
      "snomed_ct": "287572005",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Magnetic resonance imaging (MRI) of brain, without and with contrast.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0071046",
    "composition": {
      "target": "chest",
      "action": "projection radiography",
      "means": "X-ray"
    },
    "plain_language": {
      "en": "Chest X-ray (two standard angles)",
      "es": "Radiografía de tórax (dos vistas estándar)",
      "fr": "Radiographie du thorax (deux clichés standard)",
      "ar": "أشعة سينية على الصدر (وضعان)",
      "hi": "छाती का एक्स-रे (दो स्टैंडर्ड एंगल्स)",
      "zh": "胸部正侧位X光成像 (双位胸片)",
      "pt": "Radiografia do tórax (duas incidências padrão)"
    },
    "crosswalks": {
      "cpt": "71046",
      "ichi": "VVV.AA.AA",
      "snomed_ct": "284347000",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Chest radiograph, 2 views standard.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0071260",
    "composition": {
      "target": "chest",
      "action": "computed tomography",
      "means": "X-ray with contrast dye"
    },
    "plain_language": {
      "en": "Chest CT scan (with contrast dye)",
      "es": "Tomografía (TAC) de tórax con contraste",
      "fr": "Scanner (TDM) du thorax avec produit de contraste",
      "ar": "أشعة مقطعية على الصدر بالصبغة",
      "hi": "कंट्रास्ट डाई के साथ छाती का सीटी स्कैन",
      "zh": "胸部增强CT扫描",
      "pt": "Tomografia computadorizada de tórax com contraste"
    },
    "crosswalks": {
      "cpt": "71260",
      "ichi": "VVV.AF.AA",
      "snomed_ct": "444390001",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Computed tomography (CT) scan of chest with contrast dye.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0072148",
    "composition": {
      "target": "lumbar spine",
      "action": "magnetic resonance imaging",
      "means": "magnetic fields without contrast dye"
    },
    "plain_language": {
      "en": "Lower back MRI scan (without contrast dye)",
      "es": "Resonancia magnética (RM) de columna lumbar sin contraste",
      "fr": "IRM de la colonne lombaire sans produit de contraste",
      "ar": "رنين مغناطيسي على الفقرات القطنية بدون صبغة",
      "hi": "बिना कंट्रास्ट डाई के पीठ के निचले हिस्से का एमआरआई स्कैन",
      "zh": "腰椎平扫核磁共振 (MRI) 扫描",
      "pt": "Ressonância magnética (RM) de coluna lombar sem contraste"
    },
    "crosswalks": {
      "cpt": "72148",
      "ichi": "VVV.AG.AA",
      "snomed_ct": "430799008",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Magnetic resonance imaging (MRI) of lumbar spinal canal, without contrast.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0073721",
    "composition": {
      "target": "knee joint",
      "action": "magnetic resonance imaging",
      "means": "magnetic fields without contrast dye"
    },
    "plain_language": {
      "en": "Knee MRI scan (without contrast dye)",
      "es": "Resonancia magnética (RM) de rodilla sin contraste",
      "fr": "IRM de l'articulation du genou sans produit de contraste",
      "ar": "رنين مغناطيسي على مفصل الركبة بدون صبغة",
      "hi": "बिना कंट्रास्ट डाई के घुटने का एमआरआई स्कैन",
      "zh": "膝关节平扫核磁共振 (MRI) 扫描",
      "pt": "Ressonância magnética (RM) de joelho sem contraste"
    },
    "crosswalks": {
      "cpt": "73721",
      "ichi": "VVV.AI.AA",
      "snomed_ct": "431940003",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Magnetic resonance imaging (MRI) of knee joint, without contrast.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0074177",
    "composition": {
      "target": "abdomen and pelvis",
      "action": "computed tomography",
      "means": "X-ray with contrast dye"
    },
    "plain_language": {
      "en": "Abdomen and pelvis CT scan (with contrast dye)",
      "es": "Tomografía (TAC) de abdomen y pelvis con contraste",
      "fr": "Scanner (TDM) de l'abdomen et du pelvis avec produit de contraste",
      "ar": "أشعة مقطعية على البطن والحوض بالصبغة",
      "hi": "कंट्रास्ट डाई के साथ पेट और पेल्विस का सीटी स्कैन",
      "zh": "腹部和盆腔增强CT扫描",
      "pt": "Tomografia computadorizada de abdômen e pelve com contraste"
    },
    "crosswalks": {
      "cpt": "74177",
      "ichi": "VVV.AB.AA",
      "snomed_ct": "418196001",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Computed tomography (CT) scan, abdomen and pelvis, with contrast.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0076856",
    "composition": {
      "target": "pelvic organs",
      "action": "ultrasonography",
      "means": "high-frequency sound waves"
    },
    "plain_language": {
      "en": "Ultrasound scan of pelvic organs",
      "es": "Ecografía de órganos pélvicos",
      "fr": "Échographie des organes pelviens",
      "ar": "أشعة فوق صوتية (سونار) على أعضاء الحوض",
      "hi": "पेल्विक अंगों का अल्ट्रासाउंड स्कैन",
      "zh": "盆腔器官超声波检查",
      "pt": "Ultrassonografia de órgãos pélvicos"
    },
    "crosswalks": {
      "cpt": "76856",
      "ichi": "VVV.AD.AA",
      "snomed_ct": "80112001",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Pelvis ultrasound, real time imaging, complete study.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0077066",
    "composition": {
      "target": "breast",
      "action": "diagnostic projection radiography",
      "means": "low-dose X-ray"
    },
    "plain_language": {
      "en": "Targeted diagnostic mammogram of both breasts",
      "es": "Mamografía de diagnóstico dirigida en ambos senos",
      "fr": "Mammographie diagnostique bilatérale ciblée",
      "ar": "أشعة سينية لتشخيص أمراض الثديين (ماموجرام تشخيصي)",
      "hi": "लक्षण दिखने पर स्तनों की जांच (डायग्नोस्टिक मैमोग्राफी)",
      "zh": "双侧乳腺病变诊断放射检查 (诊断型乳腺钼靶)",
      "pt": "Mamografia de diagnóstico dirigida em ambas as mamas"
    },
    "crosswalks": {
      "cpt": "77066",
      "ichi": "VVV.AH.AA",
      "snomed_ct": "428414002",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Diagnostic mammography, bilateral, including CAD when performed.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0077067",
    "composition": {
      "target": "breast",
      "action": "screening projection radiography",
      "means": "low-dose X-ray"
    },
    "plain_language": {
      "en": "Routine screening mammogram of both breasts",
      "es": "Mamografía de detección de rutina en ambos senos",
      "fr": "Mammographie de dépistage bilatérale de routine",
      "ar": "أشعة سينية روتينية لفحص الثديين (ماموجرام)",
      "hi": "स्तन कैंसर का पता लगाने की सामान्य जांच (मैमोग्राफी)",
      "zh": "双侧乳腺癌常规放射筛查 (乳腺钼靶)",
      "pt": "Mamografia de rastreio de rotina em ambas as mamas"
    },
    "crosswalks": {
      "cpt": "77067",
      "ichi": "VVV.AE.AA",
      "snomed_ct": "241617006",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Screening mammography, bilateral, 2-view study of each breast.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0080048",
    "composition": {
      "target": "blood specimen",
      "action": "panel basic chemistry analysis",
      "means": "photometry"
    },
    "plain_language": {
      "en": "Basic chemistry and hydration panel (BMP)",
      "es": "Panel químico básico de electrolitos y azúcar (BMP)",
      "fr": "Bilan chimique de base des électrolytes et glucose (BMP)",
      "ar": "تحليل كيمياء الدم الأساسي والسكريات والأملاح (BMP)",
      "hi": "मूल इलेक्ट्रोलाइट्स और शुगर की जांच (बीएमपी)",
      "zh": "基础代谢电解质和血糖分析 (BMP)",
      "pt": "Painel químico básico de eletrólitos e glicose (BMP)"
    },
    "crosswalks": {
      "cpt": "80048",
      "ichi": "UUU.AH.AA",
      "snomed_ct": "442296005",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Basic metabolic panel (BMP), 8 standard chemical tests.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0080053",
    "composition": {
      "target": "blood specimen",
      "action": "panel metabolic analysis",
      "means": "photometry and ion-selective electrode"
    },
    "plain_language": {
      "en": "Comprehensive body organ and electrolyte panel (CMP)",
      "es": "Panel metabólico completo de electrolitos y órganos (CMP)",
      "fr": "Bilan métabolique complet des organes et électrolytes (CMP)",
      "ar": "تحليل التمثيل الغذائي الشامل ووظائف الأعضاء والأملاح (CMP)",
      "hi": "अंगों की कार्यप्रणाली और इलेक्ट्रोलाइट्स की व्यापक जांच (सीएमपी)",
      "zh": "综合代谢功能分析 (包含肝肾功能和电解质 CMP)",
      "pt": "Painel metabólico completo de eletrólitos e órgãos (CMP)"
    },
    "crosswalks": {
      "cpt": "80053",
      "ichi": "UUU.AB.AA",
      "snomed_ct": "442087002",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Comprehensive metabolic panel (CMP), 14 standard chemical tests.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0080061",
    "composition": {
      "target": "blood specimen",
      "action": "panel lipid analysis",
      "means": "colorimetry"
    },
    "plain_language": {
      "en": "Cholesterol and fats screening test (Lipid Panel)",
      "es": "Prueba de panel de lípidos y colesterol",
      "fr": "Bilan lipidique et cholestérol (Bilan lipidique)",
      "ar": "تحليل دهون الدم والكوليسترول",
      "hi": "कोलेस्ट्रॉल और वसा की जांच (लिपिड प्रोफाइल)",
      "zh": "血脂和胆固醇筛查分析",
      "pt": "Exame de painel lipídico e colesterol"
    },
    "crosswalks": {
      "cpt": "80061",
      "ichi": "UUU.AC.AA",
      "snomed_ct": "441753009",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Lipid panel (cholesterol, triglycerides, HDL, LDL calculate).",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0081001",
    "composition": {
      "target": "urine specimen",
      "action": "automated physical and chemical analysis",
      "means": "reagent strip and microscopy"
    },
    "plain_language": {
      "en": "Urine analysis with microscope inspection",
      "es": "Análisis de orina con inspección microscópica",
      "fr": "Analyse d'urine avec examen microscopique",
      "ar": "تحليل البول مع الفحص المجهري",
      "hi": "सूक्ष्मदर्शी जांच के साथ मूत्र विश्लेषण",
      "zh": "尿液常规筛查及镜检分析 (尿常规)",
      "pt": "Análise de urina com exame microscópico"
    },
    "crosswalks": {
      "cpt": "81001",
      "ichi": "UUU.AE.AA",
      "snomed_ct": "27171005",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Urinalysis, automated with microscopy.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0082306",
    "composition": {
      "target": "blood specimen",
      "action": "vitamin assay",
      "means": "liquid chromatography and mass spectrometry"
    },
    "plain_language": {
      "en": "Vitamin D level screening blood test",
      "es": "Prueba de sangre para medir nivel de Vitamina D",
      "fr": "Test sanguin de mesure du taux de Vitamine D",
      "ar": "تحليل نسبة فيتامين د في الدم",
      "hi": "विटामिन डी का स्तर जांचने का टेस्ट",
      "zh": "维生素D含量血液分析",
      "pt": "Exame de sangue para medir nível de Vitamina D"
    },
    "crosswalks": {
      "cpt": "82306",
      "ichi": "UUU.AI.AA",
      "snomed_ct": "72886008",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Vitamin D; 25-hydroxy, includes fraction 1 and fraction 2.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0083036",
    "composition": {
      "target": "blood specimen",
      "action": "glycated hemoglobin assay",
      "means": "chromatography"
    },
    "plain_language": {
      "en": "Three-month average blood sugar test (HbA1c)",
      "es": "Prueba de promedio de azúcar de tres meses (HbA1c)",
      "fr": "Test de glycémie moyenne sur trois mois (Hémoglobine glyquée)",
      "ar": "تحليل السكر التراكمي لثلاثة أشهر (HbA1c)",
      "hi": "तीन महीने का औसत ब्लड शुगर टेस्ट (एचबीए1सी)",
      "zh": "糖化血红蛋白平均血糖分析 (HbA1c)",
      "pt": "Exame de glicose média de três meses (HbA1c)"
    },
    "crosswalks": {
      "cpt": "83036",
      "ichi": "UUU.AF.AA",
      "snomed_ct": "43396009",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Hemoglobin A1c assay.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0084443",
    "composition": {
      "target": "blood specimen",
      "action": "hormone immunoassay",
      "means": "chemiluminescence"
    },
    "plain_language": {
      "en": "Thyroid gland screening hormone test (TSH)",
      "es": "Prueba de TSH para detectar problemas de tiroides",
      "fr": "Test de TSH pour dépister les troubles de la thyroïde",
      "ar": "تحليل هرمون الغدة الدرقية (TSH)",
      "hi": "थायराइड की जांच का मुख्य हार्मोन टेस्ट (टीएसएच)",
      "zh": "甲状腺促素筛查分析 (TSH)",
      "pt": "Exame de hormônio da tireoide (TSH)"
    },
    "crosswalks": {
      "cpt": "84443",
      "ichi": "UUU.AD.AA",
      "snomed_ct": "113063009",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Thyroid stimulating hormone (TSH) assay.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0085025",
    "composition": {
      "target": "blood specimen",
      "action": "automated cell count analysis",
      "means": "flow cytometry and microscopy"
    },
    "plain_language": {
      "en": "Complete blood count with cell breakdown (CBC)",
      "es": "Recuento sanguíneo completo con recuento de células (Hemograma)",
      "fr": "Numération formule sanguine complète (NFS)",
      "ar": "تحليل صورة الدم الكاملة مع فحص الخلايا التفصيلي",
      "hi": "रक्त कोशिकाओं के विश्लेषण के साथ पूर्ण रक्त गणना (सीबीसी)",
      "zh": "全血细胞计数及分类分析 (血常规)",
      "pt": "Hemograma completo com contagem celular detalhada"
    },
    "crosswalks": {
      "cpt": "85025",
      "ichi": "UUU.AA.AA",
      "snomed_ct": "26604007",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Complete blood count (CBC), automated, and automated differential WBC count.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0085610",
    "composition": {
      "target": "blood plasma",
      "action": "coagulation time analysis",
      "means": "electromechanical clot detection"
    },
    "plain_language": {
      "en": "Blood clotting speed evaluation test (PT/INR)",
      "es": "Prueba de velocidad de coagulación de la sangre (PT/INR)",
      "fr": "Test de vitesse de coagulation sanguine (PT/INR)",
      "ar": "تحليل سرعة تجلط الدم (PT/INR)",
      "hi": "खून जमने की गति जांचने का टेस्ट (पीटी/आईएनआर)",
      "zh": "凝血时间与凝血酶原活性分析 (PT/INR)",
      "pt": "Exame de velocidade de coagulação sanguínea (PT/INR)"
    },
    "crosswalks": {
      "cpt": "85610",
      "ichi": "UUU.AG.AA",
      "snomed_ct": "34532008",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Prothrombin time (PT) / International Normalized Ratio (INR).",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0087086",
    "composition": {
      "target": "urine specimen",
      "action": "microbiological culture",
      "means": "incubation and colony identification"
    },
    "plain_language": {
      "en": "Urine infection diagnostic test (Urine Culture)",
      "es": "Cultivo de orina para diagnosticar infecciones",
      "fr": "Uroculture pour diagnostiquer une infection (ECBU)",
      "ar": "مزرعة البول لتشخيص الالتهابات والعدوى",
      "hi": "मूत्र संक्रमण का पता लगाने की जांच (यूरिन कल्चर)",
      "zh": "尿液微生物培养及菌落计数 (尿培养)",
      "pt": "Urocultura para diagnóstico de infecção urinária"
    },
    "crosswalks": {
      "cpt": "87086",
      "ichi": "UUU.AJ.AA",
      "snomed_ct": "84178007",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Urine culture, colony count with isolation and identification.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0093000",
    "composition": {
      "target": "heart",
      "action": "electrocardiogram tracking",
      "means": "12-lead electrical sensor recording"
    },
    "plain_language": {
      "en": "Standard 12-lead heart electrical test (ECG/EKG)",
      "es": "Prueba eléctrica estándar del corazón de 12 derivaciones (ECG)",
      "fr": "Électrocardiogramme standard à 12 dérivations (ECG)",
      "ar": "رسم قلب كهربائي قياسي ذو 12 قناة (ECG)",
      "hi": "हृदय की धड़कन जांचने का इलेक्ट्रिकल टेस्ट (ईसीजी)",
      "zh": "标准十二导联心电图波形测试 (ECG/EKG)",
      "pt": "Eletrocardiograma padrão de 12 derivações (ECG/EKG)"
    },
    "crosswalks": {
      "cpt": "93000",
      "ichi": "WWW.AA.AA",
      "snomed_ct": "29303009",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Electrocardiogram (ECG/EKG), 12 leads, tracing and interpretation report.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0099202",
    "composition": {
      "target": "new patient",
      "action": "evaluation and management",
      "means": "15-29 minute cognitive visit"
    },
    "plain_language": {
      "en": "Short checkup (Level 2) for a new patient",
      "es": "Chequeo médico corto (Nivel 2) para paciente nuevo",
      "fr": "Consultation médicale courte (Niveau 2) pour nouveau patient",
      "ar": "مراجعة طبية قصيرة (المستوى 2) لمريض جديد",
      "hi": "नए मरीज के लिए छोटी जांच (स्तर 2)",
      "zh": "首诊新患者的简短医疗评估（二级）",
      "pt": "Check-up médico curto (Nível 2) para paciente novo"
    },
    "crosswalks": {
      "cpt": "99202",
      "ichi": "ZZZ.AB.AA",
      "snomed_ct": "439708006",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "New patient office visit, 20 minutes, straightforward clinical decision making.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0099203",
    "composition": {
      "target": "new patient",
      "action": "evaluation and management",
      "means": "30-44 minute cognitive visit"
    },
    "plain_language": {
      "en": "Routine checkup and consultation (Level 3) for a new patient",
      "es": "Consulta médica de rutina (Nivel 3) para paciente nuevo",
      "fr": "Consultation de routine (Niveau 3) pour nouveau patient",
      "ar": "استشارة روتينية (المستوى 3) لمريض جديد",
      "hi": "नए मरीज के लिए सामान्य जांच व परामर्श (स्तर 3)",
      "zh": "首诊新患者的普通医疗评估（三级）",
      "pt": "Consulta de rotina (Nível 3) para paciente novo"
    },
    "crosswalks": {
      "cpt": "99203",
      "ichi": "ZZZ.AB.AB",
      "snomed_ct": "439708006",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "New patient office visit, 30 minutes, low complexity decision making.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0099204",
    "composition": {
      "target": "new patient",
      "action": "evaluation and management",
      "means": "45-59 minute cognitive visit"
    },
    "plain_language": {
      "en": "Detailed initial consultation (Level 4) for a new patient",
      "es": "Consulta médica inicial detallada (Nivel 4) para paciente nuevo",
      "fr": "Consultation initiale approfondie (Niveau 4) pour nouveau patient",
      "ar": "استشارة طبية أولية مفصلة (المستوى 4) لمريض جديد",
      "hi": "नए मरीज के लिए विस्तृत प्रारंभिक परामर्श (स्तर 4)",
      "zh": "首诊新患者的深度医疗评估（四级）",
      "pt": "Consulta médica inicial detalhada (Nível 4) para paciente novo"
    },
    "crosswalks": {
      "cpt": "99204",
      "ichi": "ZZZ.AB.AC",
      "snomed_ct": "439708006",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "New patient office visit, 45 minutes, moderate complexity decision making.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0099205",
    "composition": {
      "target": "new patient",
      "action": "evaluation and management",
      "means": "60-74 minute cognitive visit"
    },
    "plain_language": {
      "en": "Comprehensive medical consultation (Level 5) for a new patient",
      "es": "Consulta médica compleja inicial (Nivel 5) para paciente nuevo",
      "fr": "Consultation initiale complexe (Niveau 5) pour nouveau patient",
      "ar": "استشارة طبية أولية شاملة ومعقدة (المستوى 5) لمريض جديد",
      "hi": "नए मरीज के लिए व्यापक व जटिल परामर्श (स्तर 5)",
      "zh": "首诊新患者的高难度医疗评估（五级）",
      "pt": "Consulta médica complexa inicial (Nível 5) para paciente novo"
    },
    "crosswalks": {
      "cpt": "99205",
      "ichi": "ZZZ.AB.AD",
      "snomed_ct": "439708006",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "New patient office visit, 60 minutes, high complexity decision making.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0099212",
    "composition": {
      "target": "established patient",
      "action": "evaluation and management",
      "means": "10-19 minute cognitive visit"
    },
    "plain_language": {
      "en": "Short medical checkup (Level 2) for a regular patient",
      "es": "Chequeo médico corto (Nivel 2) para paciente establecido",
      "fr": "Consultation médicale courte (Niveau 2) pour patient régulier",
      "ar": "مراجعة طبية قصيرة (المستوى 2) لمريض مسجل",
      "hi": "नियमित मरीज के लिए छोटी स्वास्थ्य जांच (स्तर 2)",
      "zh": "常规复诊患者的简短医疗评估（二级）",
      "pt": "Check-up médico curto (Nível 2) para paciente estabelecido"
    },
    "crosswalks": {
      "cpt": "99212",
      "ichi": "ZZZ.AA.AA",
      "snomed_ct": "439708006",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Established patient office visit, 10 minutes, straightforward clinical decision making.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0099213",
    "composition": {
      "target": "established patient",
      "action": "evaluation and management",
      "means": "20-29 minute cognitive visit"
    },
    "plain_language": {
      "en": "Routine medical consultation (Level 3) for a regular patient",
      "es": "Consulta médica de rutina (Nivel 3) para paciente establecido",
      "fr": "Consultation médicale de routine (Niveau 3) pour patient régulier",
      "ar": "استشارة طبية روتينية (المستوى 3) لمريض مسجل",
      "hi": "नियमित मरीज के लिए सामान्य परामर्श (स्तर 3)",
      "zh": "常规复诊患者的普通医疗评估（三级）",
      "pt": "Consulta médica de rotina (Nível 3) para paciente estabelecido"
    },
    "crosswalks": {
      "cpt": "99213",
      "ichi": "ZZZ.AA.AB",
      "snomed_ct": "439708006",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Established patient office visit, 15 minutes, low complexity decision making.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0099214",
    "composition": {
      "target": "established patient",
      "action": "evaluation and management",
      "means": "30-39 minute cognitive visit"
    },
    "plain_language": {
      "en": "Detailed medical consultation (Level 4) for a regular patient",
      "es": "Consulta médica detallada (Nivel 4) para paciente establecido",
      "fr": "Consultation médicale approfondie (Niveau 4) pour patient régulier",
      "ar": "استشارة طبية مفصلة (المستوى 4) لمريض مسجل",
      "hi": "नियमित मरीज के लिए विस्तृत परामर्श (स्तर 4)",
      "zh": "常规复诊患者的深度医疗评估（四级）",
      "pt": "Consulta médica detalhada (Nível 4) para paciente estabelecido"
    },
    "crosswalks": {
      "cpt": "99214",
      "ichi": "ZZZ.AA.AC",
      "snomed_ct": "439708006",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Established patient office visit, 25 minutes, moderate complexity decision making.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  },
  {
    "omni_id": "OMNI-0099215",
    "composition": {
      "target": "established patient",
      "action": "evaluation and management",
      "means": "40-54 minute cognitive visit"
    },
    "plain_language": {
      "en": "Comprehensive medical consultation (Level 5) for a regular patient",
      "es": "Consulta médica compleja (Nivel 5) para paciente establecido",
      "fr": "Consultation médicale complexe (Niveau 5) pour patient régulier",
      "ar": "استشارة طبية شاملة ومعقدة (المستوى 5) لمريض مسجل",
      "hi": "नियमित मरीज के लिए व्यापक/जटिल परामर्श (स्तर 5)",
      "zh": "常规复诊患者的高难度医疗评估（五级）",
      "pt": "Consulta médica complexa (Nível 5) para paciente estabelecido"
    },
    "crosswalks": {
      "cpt": "99215",
      "ichi": "ZZZ.AA.AD",
      "snomed_ct": "439708006",
      "icd11_pcs": null,
      "icd10_cm": null
    },
    "notes": "Established patient office visit, 40 minutes, high complexity decision making.",
    "provisional": false,
    "version": "0.1.0",
    "added": "2026-05"
  }
];
