// -*- coding: utf-8 -*-
const fs = require('fs');
const path = require('path');

const codesDir = path.join(__dirname, '../data/codes');
const outputFile = path.join(__dirname, '../src/lib/seed-codes.ts');

console.log("Starting O.M.N.I. Code compilation...");

try {
  // Read all JSON files in data/codes
  const files = fs.readdirSync(codesDir).filter(f => f.endsWith('.json'));
  console.log(`Found ${files.length} codes in ${codesDir}`);

  const codesList = [];

  files.forEach(file => {
    const raw = fs.readFileSync(path.join(codesDir, file), 'utf8');
    const parsed = JSON.parse(raw);
    
    // Auto-enrich version and date if missing
    if (!parsed.version) parsed.version = "0.2.0";
    if (!parsed.added) parsed.added = "2026-05";
    
    codesList.push(parsed);
  });

  // Sort codes alphabetically by omni_id
  codesList.sort((a, b) => a.omni_id.localeCompare(b.omni_id));

  // Construct TS content
  const tsContent = `// -*- coding: utf-8 -*-
// This file is auto-generated by compile-codes.js. Do not edit manually.
import { OMNICode } from "./registry";

export const seedCodes: OMNICode[] = ${JSON.stringify(codesList, null, 2)};
`;

  // Write output
  fs.writeFileSync(outputFile, tsContent, 'utf8');
  console.log(`Successfully compiled ${codesList.length} codes into static bundle: ${outputFile}`);
} catch (err) {
  console.error("Compilation failed with error:", err);
  process.exit(1);
}
